# Generated by Django 4.2.7 on 2023-11-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('type_car', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=4)),
                ('used', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('register', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='cars_img')),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.sale')),
            ],
        ),
    ]
