# Generated by Django 4.2.7 on 2023-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(null=True, upload_to='cars_img'),
        ),
    ]
