# Generated by Django 4.2.7 on 2023-11-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cars_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='cars',
            table='cars',
        ),
    ]
