# Generated by Django 4.2.7 on 2023-11-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_cars_options_alter_cars_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='folio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
