# Generated by Django 4.2.7 on 2023-11-21 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_sale_folio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='id_product',
            new_name='product',
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='subtotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
