# Generated by Django 4.2.7 on 2023-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_rename_id_product_salesdetail_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetail',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
