# Generated by Django 4.2.7 on 2023-11-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_salesdetail_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='subtotal',
            new_name='total',
        ),
    ]
