# Generated by Django 4.2.7 on 2023-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_rename_subtotal_salesdetail_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='product',
            new_name='id_product',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='total',
        ),
        migrations.AlterField(
            model_name='sale',
            name='folio',
            field=models.CharField(auto_created=True, max_length=6, primary_key=True, serialize=False),
        ),
    ]
