# Generated by Django 4.2.7 on 2023-11-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_rename_product_salesdetail_id_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
