# Generated by Django 4.2.7 on 2023-11-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_cars_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='quantity',
        ),
    ]
