# Generated by Django 4.2.7 on 2023-11-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_remove_cars_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesdetail',
            options={},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='register',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='salesdetail',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='salesdetail',
            old_name='folio',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='register',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='sale',
            name='folio',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='sale',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salesdetail',
            table=None,
        ),
    ]
