# Generated by Django 4.2.7 on 2023-11-28 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_sale_options_alter_salesdetail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='sale',
            new_name='folio',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='folio',
        ),
        migrations.AddField(
            model_name='sale',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
