# Generated by Django 4.2.7 on 2023-11-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_alter_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
