# Generated by Django 4.2.7 on 2023-11-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_cars_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
